const esbuild = require('esbuild');
const fs = require('fs');

// Header comment for generated files
const generatedFileHeader = `/*!
 * Chat Widget - Automatically Generated File
 * 
 * WARNING: This file is automatically generated by the build system.
 * Do not modify this file directly, as your changes will be overwritten.
 * 
 * To make changes:
 * 1. Edit the source files in the src/ directory
 * 2. Run 'npm run build' to regenerate this file
 * 
 * Generated on: ${new Date().toISOString()}
 */

`;

async function build() {
  // 1. Build to src/chat-widget.js so tests and demos (which depend on src) continue to work
  await esbuild.build({
    entryPoints: ['src/entry.js'],
    bundle: true,
    outfile: 'src/chat-widget.js',
    format: 'iife',
    minify: false,
    banner: {
      js: generatedFileHeader
    }
  });

  // 2. Ensure dist and netlify/dist directories exist
  ['dist', 'netlify/dist'].forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });

  // 3. Build unminified versions
  const unminifiedTargets = ['dist/chat-widget.js', 'netlify/dist/chat-widget.js'];
  for (const outfile of unminifiedTargets) {
    await esbuild.build({
      entryPoints: ['src/entry.js'],
      bundle: true,
      outfile: outfile,
      format: 'iife',
      minify: false,
      banner: {
        // not needeed for dist files
        // js: generatedFileHeader
      }
    });
  }

  // 4. Build minified versions (no header for minified files)
  const minifiedTargets = ['dist/chat-widget.min.js', 'netlify/dist/chat-widget.min.js'];
  for (const outfile of minifiedTargets) {
    await esbuild.build({
      entryPoints: ['src/entry.js'],
      bundle: true,
      outfile: outfile,
      format: 'iife',
      minify: true,
    });
  }
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});